[FIX] account_move: compute date_last_payment bug during migration
ingadhoc/account-invoicing pull request #130
Opened 2022-03-22 17:01 UTC by augusto-weiss

2022-03-22 17:14 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-invoicing/pull/130).

2022-03-22 20:19 UTC, nicomacr requested changes
Hi @augusto-weiss ,
Excellent work.
Only one suggest to change.

2022-03-22 20:19 UTC, nicomacr commented on account_invoice_commission/models/account_move.py
> +    @api.depends('line_ids.amount_residual')
```suggestion
    @api.depends('payment_group_ids.payment_date')
```

2022-03-23 12:36 UTC, nicomacr approved these changes, later dismissed

2022-03-23 12:37 UTC, nicomacr commented
@roboadhoc r+

2022-03-25 14:48 UTC, roboadhoc commented
@augusto-weiss ya silly goose you can't reopen a PR that's been merged PR.

2022-03-25 14:48 UTC, closed without merging