[FIX]account_invoice_control: allow edit invoice
ingadhoc/account-invoicing pull request #180
Opened 2024-03-05 14:31 UTC by cav-adhoc

Adds new field restrict_edit_invoice in account.move to restrict editing invoices only for users in group_restrict_edit_invoice

2024-03-05 14:32 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-invoicing/pull/180).

2024-03-08 16:14 UTC, maq-adhoc requested changes

2024-03-08 16:14 UTC, maq-adhoc commented on account_invoice_control/__init__.py
> +from . import models
Falta en enter al final de archivo

2024-03-08 16:14 UTC, maq-adhoc commented on account_invoice_control/models/__init__.py
> +from . import account_move
Falta en enter al final de archivo

2024-03-08 16:14 UTC, maq-adhoc commented on account_invoice_control/models/account_move.py
> +            self.restrict_edit_invoice = False
Falta en enter al final de archivo

2024-03-08 19:23 UTC, maq-adhoc approved these changes

2024-03-08 19:23 UTC, maq-adhoc commented
@roboadhoc r+

2024-03-08 19:26 UTC, closed without merging