[MIG] account_invoice_commission to 11.0
ingadhoc/account-invoicing pull request #42
Opened 2018-03-26 12:58 UTC by nicomacr

2018-03-26 18:20 UTC, zaoral requested changes
@nicomacr 
Here I leave you some comments, please review when you can.

Best Regards

2018-03-26 18:20 UTC, zaoral commented on account_invoice_commission/README.rst
> +   :target: http://runbot.adhoc.com.ar/
```
+   :target: http://runbot.adhoc.com.ar/
```
Need to be https: http page does not work.

2018-03-26 18:20 UTC, zaoral commented on account_invoice_commission/models/account_invoice.py
>          compute='_compute_partner_user',
remove line

```
 # from odoo.exceptions import ValidationError
```
is really not used

2018-03-26 18:20 UTC, zaoral commented on account_invoice_commission/models/account_invoice_line.py
>      def _compute_commission_amount(self):
@nicomacr Why you removed the api.depends from this method?

2018-03-26 18:20 UTC, zaoral commented on account_invoice_commission/views/account_invoice_view.xml
> +                    <field name="commissioned_invoice_ids"  context="{'commissioned_partner_id': partner_id, 'tree_view_ref':'account_invoice_commission.invoice_tree', 'form_view_ref':'account.invoic
avoid extra space after before context option added when updating in this line

2018-03-26 18:20 UTC, zaoral commented on account_invoice_commission/models/account_invoice_line.py
> +            _logger.info('Computing commission amount line')
Should we use _() for translation?

2018-03-26 19:34 UTC, zaoral commented on account_invoice_commission/README.rst
> +   :target: http://runbot.adhoc.com.ar/
sorry, my mistake. it's the opposite. http is the one that works.
Do not take into account this comment.

2018-03-26 22:24 UTC, jjscarafia commented on account_invoice_commission/models/account_invoice_line.py
> +            _logger.info('Computing commission amount line')
for log messages it seams better to me to keep them in english (without translation)

2018-04-04 17:33 UTC, merged

2018-04-04 19:26 UTC, zaoral commented on account_invoice_commission/models/account_invoice_line.py
> +            _logger.info('Computing commission amount line')
> for log messages it seams better to me to keep them in english (without translation)

ok. good to know